/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountPassword: typeof import('./../src/components/LoginDialog/components/FormLogin/AccountPassword.vue')['default']
    AiSender: typeof import('./../src/components/AiSender/index.vue')['default']
    BubbleList: typeof import('./../src/components/BubbleList/index.vue')['default']
    Conversations: typeof import('./../src/components/Conversations/index.vue')['default']
    DeepThinking: typeof import('./../src/components/DeepThinking/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpin: typeof import('element-plus/es')['ElSpin']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilesSelect: typeof import('./../src/components/FilesSelect/index.vue')['default']
    IconSelect: typeof import('./../src/components/IconSelect/index.vue')['default']
    LoginDialog: typeof import('./../src/components/LoginDialog/index.vue')['default']
    ModelSelect: typeof import('./../src/components/ModelSelect/index.vue')['default']
    Popover: typeof import('./../src/components/Popover/index.vue')['default']
    QrCodeLogin: typeof import('./../src/components/LoginDialog/components/QrCodeLogin/index.vue')['default']
    RegistrationForm: typeof import('./../src/components/LoginDialog/components/FormLogin/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TypeingText: typeof import('./../src/components/TypeingText/index.vue')['default']
    TypeText: typeof import('./../src/components/TypeText/index.vue')['default']
    TypewriterText: typeof import('./../src/components/TypewriterText/index.vue')['default']
    TypingText: typeof import('./../src/components/TypingText/index.vue')['default']
    VerificationCode: typeof import('./../src/components/LoginDialog/components/FormLogin/VerificationCode.vue')['default']
    WelcomeText: typeof import('./../src/components/WelcomeText/index.vue')['default']
    WelecomeText: typeof import('./../src/components/WelecomeText/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
